#!/bin/bash

SKIP_FILENAME_CHECKS_ON_WSL=false

cmd_args=("$@")
case $# in
	0)
		echo "please run the script with the rom (and the .sav) as arguments"
		;;
	1)
        extension="${1##*.}"
        if [[ "${extension^^}" == "GBC" ]]; then rom_filename="$1"; save_filename="${1%.*}.sav" ; fi
        if [[ "${extension^^}" == "GB"  ]]; then rom_filename="$1"; save_filename="${1%.*}.sav" ; fi
		;;
	2)
		for arg	in "${cmd_args[@]}"; do
			extension="${arg##*.}"
			if [[ "${extension^^}" == "SAV" ]]; then save_filename="$arg"; fi
			if [[ "${extension^^}" == "GBC" ]]; then  rom_filename="$arg"; fi
			if [[ "${extension^^}" == "GB"  ]]; then  rom_filename="$arg"; fi
		done
		;;
	*)
		echo "too many arguments"
		echo "please run the script with the rom (and the .sav) as arguments"
		;;
esac

if [[ "$SKIP_FILENAME_CHECKS_ON_WSL" == "true" && -e /proc/sys/fs/binfmt_misc/WSLInterop ]]; then
    echo "Windows for Linux Subsystem detected"
    save_exists=true
else
  if [ ! -f "$save_filename" ]; then
    echo "$save_filename is not a regular file"
    save_exists=false
  else
    save_exists=true
  fi

  if [ ! -f "$rom_filename" ]; then
    echo "$rom_filename is not a regular file"
    exit 1
  fi
fi

function copy_sav_to_game {
    printf "\n\n\tCreating ROM backup...\n"
    cp "$rom_filename" "${rom_filename%.*}.backup_$(date +%F_%Hh%Im%Ss).${rom_filename##*.}" && printf "\tBackup successful. File: ${rom_filename%.*}.backup_$(date +%F_%Hh%Im%Ss).${rom_filename##*.}\n\n"
    dd bs=1          seek=$(( ($bank_number + 0) * 0x4000 + 0x2000 )) count=8k status=none conv=notrunc if="$save_filename" of="$rom_filename"
    dd bs=1 skip=8k  seek=$(( ($bank_number + 1) * 0x4000 + 0x2000 )) count=8k status=none conv=notrunc if="$save_filename" of="$rom_filename"
    dd bs=1 skip=16k seek=$(( ($bank_number + 2) * 0x4000 + 0x2000 )) count=8k status=none conv=notrunc if="$save_filename" of="$rom_filename"
    dd bs=1 skip=24k seek=$(( ($bank_number + 3) * 0x4000 + 0x2000 )) count=8k status=none conv=notrunc if="$save_filename" of="$rom_filename"
    printf "\n\tInjection finished.\n\tNow re-write the ROM into the game cartridge.\n\n"
}

function copy_sav_from_game {
    if [[ "$save_exists" == "true" ]] ; then
        printf "\n\n\tCreating SAV backup...\n"
        cp "$save_filename" "${save_filename%.*}.backup_$(date +%F_%Hh%Im%Ss).${save_filename##*.}" && printf "\tBackup successful. File: ${save_filename%.*}.backup_$(date +%F_%Hh%Im%Ss).${save_filename##*.}\n\n"
    fi
    dd bs=1 skip=$(( ($bank_number + 0) * 0x4000 + 0x2000 ))          count=8k status=none conv=notrunc if="$rom_filename" of="$save_filename"
    dd bs=1 skip=$(( ($bank_number + 1) * 0x4000 + 0x2000 )) seek=8k  count=8k status=none conv=notrunc if="$rom_filename" of="$save_filename"
    dd bs=1 skip=$(( ($bank_number + 2) * 0x4000 + 0x2000 )) seek=16k count=8k status=none conv=notrunc if="$rom_filename" of="$save_filename"
    dd bs=1 skip=$(( ($bank_number + 3) * 0x4000 + 0x2000 )) seek=24k count=8k status=none conv=notrunc if="$rom_filename" of="$save_filename"
    printf "\n\tExtraction finished.\n\t$save_filename now contains the save from the ROM.\n\n"
}

# if two banks after another contain only 0xFF in the first half and other data in the second half, then it might be save data
function check_bank_for_sav {
    if [[ "$(dd bs=1 skip=$(( ($1 + 0) * 0x4000          )) count=8k status=none conv=notrunc if="$rom_filename" | sha1sum)" == "5e2b96c19c4f5c63a5afa2de504d29fe64a4c908  -" && \
          "$(dd bs=1 skip=$(( ($1 + 0) * 0x4000 + 0x2000 )) count=8k status=none conv=notrunc if="$rom_filename" | sha1sum)" != "5e2b96c19c4f5c63a5afa2de504d29fe64a4c908  -" && \
          "$(dd bs=1 skip=$(( ($1 + 1) * 0x4000          )) count=8k status=none conv=notrunc if="$rom_filename" | sha1sum)" == "5e2b96c19c4f5c63a5afa2de504d29fe64a4c908  -" && \
          "$(dd bs=1 skip=$(( ($1 + 1) * 0x4000 + 0x2000 )) count=8k status=none conv=notrunc if="$rom_filename" | sha1sum)" != "5e2b96c19c4f5c63a5afa2de504d29fe64a4c908  -" && \
          "$(dd bs=1 skip=$(( ($1 + 2) * 0x4000          )) count=8k status=none conv=notrunc if="$rom_filename" | sha1sum)" == "5e2b96c19c4f5c63a5afa2de504d29fe64a4c908  -" ]]; then
          bank_number=$1
    fi
}

banks_in_rom=$(( $(stat -c%s "$rom_filename") / 0x4000 ))
i=$banks_in_rom
until [ $i -le 8 ] ; do
    i=$(( $i - 4))
    check_bank_for_sav $i
done

if [[ "$bank_number" != "" ]]; then
    printf "\n\tbank autodetected: $(printf '0x%x' $bank_number)\n\n"
    read -p "        use autodetected bank [Enter] or enter Banknumber in 0x00 format: --> " ver
else
    read -p "        enter Banknumber in 0x00 format: --> " ver
fi

if [ "$ver" = "" ]; then
    if [[ $(( $bank_number )) -gt 0 && $(( $bank_number )) -le $banks_in_rom ]]; then true; else exit 1; fi
elif [[ $(( $ver )) -gt 0 && $(( $ver )) -le $banks_in_rom ]]; then
        bank_number="$var"
else
    echo "no valid input"
    exit 1
fi

if [[ "$save_exists" == "true" ]] ; then
    echo ""
    read -p "        Copy from game to sav [1] or from sav to game [2]? --> " copy
else
    copy="1"
    echo ""
    echo "copying save from rom"
fi

if [ "$copy" = "1" ]; then
    copy_sav_from_game
elif [ "$copy" = "2" ]; then
    copy_sav_to_game
else
    echo "no copy mode selected"
    exit 1
fi

